EulerFrame pose # Requested pose
float32[] initial_joints # Joints in radians, empty if current pose used
---
float32[] joints # Joints in radians
# error: 0 on SUCCESS
#        1 when initial_joints size > 0
#        2 when NO solution was found for IK
int32 error 
